set_charging_amps:
  fields:
    amps:
      required: false
      selector:
        number:
          min: 5
          max: 16
          unit_of_measurement: "A"
    entity_amps:
      required: false
      selector:
        entity:
          domain: sensor
    vehicle:
      required: true
      selector:
        device:
          integration: tessie
set_climate_temp:
  fields:
    temp:
      required: true
      selector:
        number:
          min: 0
          max: 40
    vehicle:
      required: true
      selector:
        device:
          integration: tessie
