name: Validate

on:
  push:
  pull_request:

jobs:
  validate-with-hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
